logging:
  level:
    root: DEBUG
    org.springframework: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    org.springframework.web: DEBUG


server:
  port: 9278
  error:
    include-message: ALWAYS
    include-binding-errors: ALWAYS
    include-stacktrace: ALWAYS
    include-exception: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/interviewgene?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    hikari:
      auto-commit: false
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        type:
          descriptor:
            sql: trace
        jdbc:
          time_zone: UTC
        connection:
          provider_disables_autocommit: false
        criteria:
          literal_handling_mode: BIND

    hibernate:
      ddl-auto: update   # update/create/update schema automatically (dev only)

  hikari:
    minimum-idle: 2
    maximum-pool-size: 10
    idle-timeout: 10000
    max-lifetime: 2000000


jwt:
  secret: TfLuSdOboUoHoSkNdUI0Tjp5u12T4HyR
  expiration-ms: 3600000

